qc_demo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('samples.urls')),
]

samples/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # for samples
    path("", views.IndexTemplateView.as_view(), name="index"),
    path("samples/", views.SampleListView.as_view(), name="sample-list"),
    path("samples/new/", views.SampleCreateView.as_view(), name="sample-new"),
    path("samples/<int:pk>/detail/", views.SampleDetailView.as_view(), name="sample-detail"),

    # for obs
    path("samples/<int:sample>/new-observation/", views.ObservationCreateView.as_view(), name="obs-new"),
    path("observation/<int:pk>/edit/", views.ObservationUpdateView.as_view(), name="obs-edit"),
]

samples/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


#
# class Species(models.Model):
#     code = models.IntegerField(blank=True, null=True, unique=True, verbose_name="code")
#     common_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="English common name")
#     scientific_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Scientific name")
#     tsn = models.IntegerField(blank=True, null=True, verbose_name="ITIS TSN")
#
#     def __str__(self):
#         return self.common_name


class Sample(models.Model):
    date = models.DateTimeField(blank=True, null=True, default=timezone.now)
    sampler_name = models.CharField(max_length=100, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Sample #{self.id}"

    class Meta:
        ordering = ['date']

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("sample-detail", args=[self.pk])

class Observation(models.Model):
    sex_choices = (
        (1, "1-female"),
        (2, "2-male"),
        (9, "9-unknown"),
    )

    maturity_choices = (
        (1, "1-young"),
        (2, "2-old"),
        (2, "3-really old"),
        (9, "9-unknown"),
    )

    sample = models.ForeignKey(Sample, related_name="observations", on_delete=models.CASCADE)
    # species = models.ForeignKey(Species, related_name="fish_details", on_delete=models.CASCADE)
    length = models.FloatField()
    weight = models.FloatField()
    sex = models.IntegerField(choices=sex_choices)
    maturity = models.IntegerField(choices=maturity_choices)
    remarks = models.TextField(null=True, blank=True)
    gonad_weight = models.FloatField(null=True, blank=True)
    parasite = models.NullBooleanField()

    class Meta:
        pass

    def __str__(self):
        return f"fishy #{self.id} [sex={self.get_sex_display()} - length={self.length}mm - weight={self.weight}g]"

    @property
    def length_to_weight_ratio(self):
        return self.length / self.weight

    def get_absolute_url(self):
        return reverse("sample-detail", args=[self.sample.pk])

samples/forms.py
from django import forms
from . import models

class ObservationForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = models.Observation
        widgets = {
            "sample":forms.HiddenInput()
        }

samples/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import UpdateView, CreateView, DetailView, ListView, TemplateView
from . import models
from . import forms


class IndexTemplateView(TemplateView):
    template_name = 'samples/index.html'


class SampleListView(ListView):
    model = models.Sample


class SampleCreateView(CreateView):
    model = models.Sample
    fields = "__all__"


class SampleDetailView(DetailView):
    model = models.Sample


class ObservationCreateView(CreateView):
    model = models.Observation
    form_class = forms.ObservationForm

    def get_initial(self):
        return {"sample": self.kwargs["sample"]}


class ObservationUpdateView(UpdateView):
    model = models.Observation
    form_class = forms.ObservationForm

samples/templates/samples/_style.html
<style>
    body {
        margin-left: 200px;
    }

    table {
        border: 1px solid black;
        text-align: left;
    }

    td, th {
        padding-left: 20px;
        padding-right: 20px;
    }
</style>

samples/templates/samples/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fish Sampling</title>
    {% include "samples/_style.html" %}

</head>
<body>
<h1>
    Welcome to our site
</h1>
<img src="https://www.pac.dfo-mpo.gc.ca/sep-pmvs/images/salmon-saumon.jpg" alt="">
<br>

<a href="{% url 'sample-list' %}">Click here to view samples</a>

</body>
</html>

samples/templates/samples/observation_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include "samples/_style.html" %}

</head>
<body>
<h1>
    {% if object %}
        {{ object }}
    {% else %}
        Create a new sample
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

</body>
</html>

samples/templates/samples/sample_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fish Sampling</title>
    {% include "samples/_style.html" %}
</head>
<body>
<h1>
    {{ object }}
</h1>
<a href="{% url 'sample-list' %}">back to sample list</a>
<br>
<br>
<table>
    <tr>
        <th>id</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>sampler name</th>
        <td>{{ object.sampler_name }}</td>
    </tr>
    <tr>
        <th>location</th>
        <td>{{ object.location }}</td>
    </tr>
    <tr>
        <th>remarks</th>
        <td>{{ object.remarks }}</td>
    </tr>
</table>

<br>
<br>


<a href="{% url 'obs-new' object.id %}">new observation</a>
<h3>Here is a list of related observations</h3>

<table>


    <thead>
    <th>id</th>
    <th>length</th>
    <th>weight</th>
    <th>sex</th>
    <th>maturity</th>
    <th>gonad weight</th>
    <th>parasites?</th>
    <th>remarks</th>


    </thead>
    <tbody>
    {% for obs in object.observations.all %}
        <tr>
            <td>{{ obs.id }}</td>
            <td>{{ obs.length }}</td>
            <td>{{ obs.weight }}</td>
            <td>{{ obs.get_sex_display }}</td>
            <td>{{ obs.get_maturity_display }}</td>
            <td>{{ obs.gonad_weight }}</td>
            <td>{{ obs.parasite }}</td>
            <td>{{ obs.remarks }}</td>
            <td>

                (<a href="{% url 'obs-edit' obs.id %}">edit</a>)
            </td>
        </tr>
    {% endfor %}

    </tbody>
</table>


</body>
</html>

samples/templates/samples/sample_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fish Sampling</title>
    {% include "samples/_style.html" %}

</head>
<body>
<h1>
    {% if object %}
        {{ object }}
    {% else %}
        Create a new sample
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

</body>
</html>

samples/templates/samples/sample_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fish Sampling</title>
    {% include "samples/_style.html" %}
</head>
<body>
<h1>
    Here are a list of samples
</h1>

<a href="{% url 'index' %}">home</a> <br>
<a href="{% url 'sample-new' %}">create a new sample</a>
<br>
<br>

<table>
    <thead>
    <th>id</th>
    <th>date</th>
    <th>sampler name</th>
    <th>location</th>
    </thead>
    <tbody>

    {% for object in object_list %}
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.date }}</td>
            <td>{{ object.sampler_name }}</td>
            <td>{{ object.location }}</td>
            <td>(<a href="{% url 'sample-detail' object.id %}">view details</a>)</td>
        </tr>
    {% endfor %}

    </tbody>


</table>

</body>
</html>